version: '3.9'

networks:
  nestjs-rabbitmq-network:
    name: nestjs-rabbitmq-network
    driver: bridge

services:
  nestjs-rabbitmq-consumer:
    build: .
    container_name: nestjs-rabbitmq-consumer
    image: nestjs-rabbitmq-consumer:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    networks:
      - nestjs-rabbitmq-network